spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.default-schema=autopayment
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
logging.level.root=INFO

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Кастомные метрики
management.metrics.enable.all=true
management.metrics.export.prometheus.enabled=true

# Graceful shutdown
spring.lifecycle.timeout-per-shutdown-phase=30s
server.shutdown=graceful

# Quartz Scheduler
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.jobStore.useProperties=true
spring.quartz.properties.org.quartz.scheduler.instanceName=AutopayScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.jobStore.tablePrefix=autopayment.qrtz_

# Остальные настройки остаются без изменений
# Добавляем настройки для Retry (опционально, можно оставить дефолтные)
spring.retry.max-attempts=3