spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# Показываем SQL запросы
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# Liquibase
spring.liquibase.default-schema=autopayment
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
logging.level.root=INFO

# ====== ВКЛЮЧАЕМ ВСЕ ЛОГИ ======


# Логируем все SQL с параметрами
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=TRACE

# Логируем транзакции
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

# Логируем выполнение запросов
logging.level.org.hibernate.engine.jdbc.batch=DEBUG
logging.level.org.hibernate.engine.jdbc.connections=DEBUG

# Логируем сам тест
logging.level.com.bank.autopay=DEBUG